### ISSUE TITLE
Service framework: AAA

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#31]
Authentication, Authorization and Accounting service, which takes care of user accounts, authroization, groups, and permissions.

**Comment by hakusaro** [comment]
@tylerjwatson just wanted your input on whether or not AAA is destined to have user facing entry points (commands)?

**Comment by hakusaro** [comment]
@Enerdy it's been several months. Is there something blocking you on this that we can help you out with?

**Comment by AxisKriel** [comment]
So stuff happened and been busy with other projects. I've previously been stuck on an issue with permissions but that has since been addressed on Slack. I'll see if I can spare some time and start committing instead of leaving everything for a single big commit (which I tend to do).

On 23 Oct 2016, at 20:28, Lucas Nicodemus <notifications@github.com<mailto:notifications@github.com>> wrote:

@Enerdyhttps://github.com/Enerdy it's been several months. Is there something blocking you on this that we can help you out with?

##

**Comment by Ijwu** [comment]
@Enerdy Feel free to include that Slack discussion in the GitHub Issues correspondence. It helps provide context.

**Comment by kevzhao2** [comment]
Closing this, as it will be handled in TShock.
